"""Build the Records catalogue from dated, cited public snapshots.
Downloaded OWID CSV inputs are in /tmp/flagbook-series; see data/SOURCES.md.
"""
import json,csv,pathlib
ROOT=pathlib.Path(__file__).resolve().parents[1]
details=json.loads((ROOT/'data/country-details.json').read_text())
countries=json.load(open('/tmp/flag-countries-source.json'));by3={c['cca3']:c['cca2'].lower() for c in countries if c['cca2'].lower() in details}
items=[]
def add(id,category,label,unit,year,art,note,source,entries,**extra):
 entries=sorted(entries,key=lambda r:-r['value'])
 for i,e in enumerate(entries):e['rank']=1+sum(r['value']>e['value'] for r in entries)
 items.append(dict(id=id,category=category,label=label,unit=unit,year=year,art=art,note=note,source=source,entries=entries,**extra))
for id,label,slug,note in [('coffee','Coffee beans','coffee-bean-production','Unroasted green beans; production, not exports or cups consumed.'),('cocoa','Cocoa beans','cocoa-bean-production','Harvested cocoa beans; production, not chocolate manufacturing.'),('rice','Rice','rice-production','Paddy rice before milling; production, not rice exports.'),('wheat','Wheat','wheat-production','Annual harvested wheat production.'),('maize','Maize','maize-production','Annual maize (corn) production.'),('sugarcane','Sugar cane','sugar-cane-production','Harvested cane weight, not the weight of refined sugar.')]:
 rows=list(csv.DictReader(open('/tmp/flagbook-series/'+slug+'.csv')));year=max(int(r['Year']) for r in rows);key=list(rows[0])[-1]
 entries=[{'code':by3[r['Code']],'value':float(r[key])} for r in rows if r['Code'] in by3 and int(r['Year'])==year and r[key] and float(r[key])>0]
 add(id,'Agriculture',label,'tonnes',str(year),'crops',note,'https://ourworldindata.org/grapher/'+slug,entries,sourceLabel='FAOSTAT / Our World in Data',coverage='Reporting countries in the 195-country learning set. Regional aggregates excluded.')
for id,label in [('oil','Oil production'),('gas','Natural gas production')]:
 rows=list(csv.DictReader(open('/tmp/flagbook-series/'+id+'.csv')));year=max(int(r['Year']) for r in rows);key=list(rows[0])[-1]
 entries=[{'code':by3[r['Code']],'value':float(r[key])} for r in rows if r['Code'] in by3 and int(r['Year'])==year and r[key] and float(r[key])>0]
 note='Energy content of production, in terawatt-hours. '+('Includes crude oil, condensates, natural gas liquids and other liquid fuels.' if id=='oil' else 'Production of natural gas, expressed as energy rather than volume.')
 add(id,'Industry',label,'TWh',str(year),'industry',note,f'https://ourworldindata.org/grapher/fossil-fuels?fuel={id}&metric=production&per_capita=total',entries,sourceLabel='Energy Institute / EIA / Our World in Data',coverage='Reporting countries in the learning set, same observation year.')
for id,category,label,values,note in [
 ('cotton','Textiles','Cotton lint production',{'cn':35800,'in':23800,'br':18750,'us':13897,'pk':5300,'au':4500,'uz':3445},'Cotton lint after ginning; preliminary 2025/26 marketing-year estimates, September 2026 report.'),
 ('cotton-mills','Textiles','Cotton mill use',{'cn':41600,'in':26000,'pk':9900,'vn':8150,'bd':7400,'tr':6800,'uz':4000,'br':3350,'id':2050,'us':1500},'Cotton consumed by mills: a textile-processing measure, not the value of garment exports. Preliminary 2025/26 estimates.'),
 ('cotton-exports','Textiles','Cotton lint exports',{'br':15497,'us':12300,'au':5592,'in':1100,'bj':1150,'gr':1050,'ml':900,'bf':600,'ci':624,'tr':1103},'Raw cotton lint exported; not finished clothing. Preliminary 2025/26 estimates, September 2026 report.')]:
  add(id,category,label,'480-lb bales','2025/26','textiles',note,'https://apps.fas.usda.gov/psdonline/circulars/cotton.pdf',[{'code':c,'value':v*1000} for c,v in values.items()],sourceLabel='USDA · September 2026 · table 02',coverage='Leading countries individually listed in USDA table 02. Only covered countries receive a rank.')
for id,label,category,indicator in [('services','Services exports','Services','BX.GSR.NFSV.CD'),('manufacturing','Manufacturing value added','Industry','NV.IND.MANF.CD')]:
 data=json.load(open('/tmp/flagbook-'+id+'.json'))
 entries=[{'code':by3[r['countryiso3code']],'value':r['value']} for r in data[1] if r['countryiso3code'] in by3 and r['value'] is not None and r['value']>0]
 add(id,category,label,'US$','2024','industry' if category=='Industry' else 'services','Current US dollars; compare absolute economic size, not share of GDP or output per person.','https://data.worldbank.org/indicator/'+indicator,entries,sourceLabel='World Bank',coverage='2024 reporting countries in the learning set; missing observations excluded.')
tourism=json.loads((ROOT/'data/editorial/tourism-benchmark.json').read_text())['observations']
add('tourism','Services','International arrivals','arrivals','2019','services','Historical pre-pandemic benchmark. Counts trips, not unique visitors; this is not a current travel ranking.','https://data.worldbank.org/indicator/ST.INT.ARVL',[{'code':c,'value':v['arrivals']} for c,v in tourism.items() if v and v['year']==2019],sourceLabel='World Bank / UN Tourism',coverage='Only countries reporting 2019, without mixing older years.')
WORLD='https://github.com/factbook/factbook.json/blob/144d6977b2b01ac1cbd220de754c0a005616760b/world/xx.json'
rivers=[('Nile',6650,['rw','tz','ug','ss','sd','eg'],'East African headwaters → Lake Victoria / White Nile; Blue Nile from Ethiopia → Mediterranean Sea.','The White and Blue Nile meet at Khartoum. Tributaries and the basin extend beyond the countries on the main course.'),('Amazon',6436,['pe','co','br'],'Andean headwaters in Peru → across northern Brazil → Atlantic Ocean.','The Amazon carries more water than any other river. Its longest headwater and total length remain debated.'),('Yangtze',6300,['cn'],'Tibetan Plateau → central and eastern China → East China Sea.','China’s longest river is also called Chang Jiang.'),('Mississippi–Missouri',6275,['us'],'Rocky Mountain headwaters → Missouri → Mississippi → Gulf of Mexico.','This ranking measures the connected river system, not the Mississippi main stem alone.'),('Yenisey–Angara',5539,['mn','ru'],'Mongolian headwaters / Lake Baikal tributary system → Siberia → Kara Sea.','A connected system flowing north toward the Arctic Ocean.')]
add('rivers','Nature','Longest river systems','km','Geographic reference','rivers','Approximate whole-system lengths. Sources differ on headwaters and measurement; the Nile–Amazon order is disputed. Country lists describe the course, not every country in the drainage basin.',WORLD,[{'name':n,'value':v,'countries':cs,'route':r,'detail':d} for n,v,cs,r,d in rivers],sourceLabel='World Factbook · world geography',coverage='Five longest river systems in this source’s convention.')
peaks=[('Mount Everest',8848.86,['np','cn'],'Himalayas · Nepal–China border'),('K2',8611,['pk','cn'],'Karakoram · Pakistan-administered Kashmir–China border'),('Kanchenjunga',8586,['in','np'],'Himalayas · India–Nepal border'),('Lhotse',8516,['np','cn'],'Himalayas · Nepal–China border'),('Makalu',8463,['np','cn'],'Himalayas · Nepal–China border')]
add('mountains','Nature','Highest mountains','m','Geographic reference','mountains','Elevation above sea level, not height from base. Makalu follows the Nepal tourism reference (8,463 m); other surveys commonly quote 8,485 m.','https://tourismdepartment.gov.np/pages/mountains1/',[{'name':n,'value':v,'countries':cs,'route':r,'detail':'Shared summits belong to both sides of the border.'} for n,v,cs,r in peaks],sourceLabel='Nepal Department of Tourism / country high-point records',coverage='Five highest independent summits. Border descriptions do not resolve territorial claims.')
volcanoes=[('Nevados Ojos del Salado',6879,['cl','ar']),('Llullaillaco',6739,['cl','ar']),('Tipas',6658,['ar']),('Nevado de Incahuasi',6638,['cl','ar']),('Coropuna',6377,['pe'])]
add('volcanoes','Nature','Highest Holocene volcanoes','m','Geographic reference','volcanoes','Smithsonian’s Holocene-volcano list, measured above sea level. This excludes older extinct volcanic mountains and is not a ranking by height from the ocean floor.','https://volcano.si.edu/faq/index.cfm?question=highestvolcano',[{'name':n,'value':v,'countries':cs,'route':'Andes · South America','detail':'Elevation follows the Smithsonian Global Volcanism Program reference table.'} for n,v,cs in volcanoes],sourceLabel='Smithsonian Global Volcanism Program',coverage='Five highest volcanoes in the cited Holocene list.')
(ROOT/'data/world-records.json').write_text(json.dumps({'checked':'2026-09-29','items':items},ensure_ascii=False,separators=(',',':'))+'\n')
print('Built',len(items),'record topics and',sum(len(i['entries']) for i in items),'ranked entries.')
